import abc
from typing import List, Dict, Optional, Any
from ..types.page.fingerprint import PageFingerprint


class PersistenceStore(abc.ABC):
    @abc.abstractmethod
    def save_seed(self, query: str, entity_type: str, source: str): ...
    @abc.abstractmethod
    def save_page(self, page: Dict): ...
    @abc.abstractmethod
    def save_links(self, from_url: str, links: List[Dict]): ...
    @abc.abstractmethod
    def save_fingerprint(self, fp: PageFingerprint): ...
    @abc.abstractmethod
    def save_patterns(self, patterns: List[Dict]): ...
    @abc.abstractmethod
    def save_domains(self, domains: List[Dict]): ...
    @abc.abstractmethod
    def get_pending_refresh(self, limit: int = 50) -> List[Dict]: ...
    @abc.abstractmethod
    def mark_visited(self, url: str): ...
    @abc.abstractmethod
    def has_visited(self, url: str) -> bool: ...
